
import csv

translations = {
    "Move Forward": "Mover Adelante",
    "Move Backward": "Mover Atrás",
    "Move Left": "Mover Izquierda",
    "Move Right": "Mover Derecha",
    "Sprint": "Correr",
    "Jump": "Saltar",
    "Crouch": "Agacharse",
    "Use": "Usar",
    "Examine": "Examinar",
    "Fire": "Disparar",
    "Reload": "Recargar",
    "ADS": "Apuntar",
    "Equip 1": "Equipar 1",
    "Equip 2": "Equipar 2",
    "Equip 3": "Equipar 3",
    "Equip 4": "Equipar 4",
    "Unequip": "Desequipar",
    "Lean Right": "Inclinarse Derecha",
    "Lean Left": "Inclinarse Izquierda",
    "Flashlight": "Linterna",
    "Load Game": "Cargar Partida",
    "Options": "Opciones",
    "Pause Menu": "Menú de Pausa",
    "Resume": "Reanudar",
    "Continue": "Continuar",
    "New Game": "Nueva Partida",
    "Save Game": "Guardar Partida",
    "Quit": "Salir",
    "Restart": "Reiniciar",
    "Main Menu": "Menú Principal",
    "Back": "Volver",
    "Load": "Cargar",
    "Delete": "Eliminar",
    "Apply": "Aplicar",
    "Reset": "Restablecer",
    "Resume your saved progress": "Reanudar tu progreso guardado",
    "Continue playing game": "Continuar jugando",
    "Start a new game": "Iniciar una nueva partida",
    "Load a previously saved games": "Cargar una partida guardada anteriormente",
    "Save your current progress": "Guardar tu progreso actual",
    "Adjust game settings and preferences": "Ajustar configuración y preferencias del juego",
    "Exit the game": "Salir del juego",
    "Start the game from your most recent saved data": "Iniciar el juego desde tu último guardado",
    "Exit the game and go to the main menu": "Salir del juego y volver al menú principal",
    "Press Button": "Presionar Botón",
    "None": "Ninguno",
    "Key Bindings": "Teclas de Control",
    "There are currently no saved games available.": "Actualmente no hay partidas guardadas disponibles.",
    "You have died": "Has muerto",
    "Put Away": "Guardar",
    "Take": "Tomar",
    "Rotate": "Rotar",
    "Looted": "Saqueado",
    "Insert Tape": "Insertar Cinta",
    "Power On": "Encender",
    "Power Off": "Apagar",
    "Eject Tape": "Expulsar Cinta",
    "Play": "Reproducir",
    "Pause": "Pausar",
    "Rewind": "Rebobinar",
    "Fast Forward": "Avance Rápido",
    "Lockpicks: [count]": "Ganzúas: [count]",
    "Use (Hold)": "Usar (Mantener)",
    "Grab": "Agarrar",
    "Travel": "Viajar",
    "Configure": "Configurar",
    "Insert Fuse": "Insertar Fusible",
    "Enter Code": "Ingresar Código",
    "Use Keycard": "Usar Tarjeta",
    "Switch": "Interruptor",
    "Switch On": "Encender",
    "Switch Off": "Apagar",
    "Extinguish": "Extinguir",
    "Kindle (Hold)": "Encender (Mantener)",
    "Refuel (Hold)": "Reabastecer (Mantener)",
    "Hide": "Esconderse",
    "Get Out": "Salir",
    "Open": "Abrir",
    "Close": "Cerrar",
    "Electric Circuit": "Circuito Eléctrico",
    "Fusebox": "Caja de Fusibles",
    "Keypad": "Teclado Numérico",
    "Keycard": "Tarjeta de Acceso",
    "Padlock": "Candado",
    "Lever": "Palanca",
    "Panel Door": "Puerta de Panel",
    "Door": "Puerta",
    "Valve": "Válvula",
    "Drawer": "Cajón",
    "Storage Trunk": "Baúl de Almacenamiento",
    "Backpack": "Mochila",
    "Crate": "Cajón de Madera",
    "Barrel": "Barril",
    "Brick": "Ladrillo",
    "Pushable": "Empujable",
    "Ladder": "Escalera",
    "Zipline": "Tirolesa",
    "Paper": "Papel",
    "Chest": "Cofre",
    "Lamp": "Lámpara",
    "Power Generator": "Generador Eléctrico",
    "Radio": "Radio",
    "Locker": "Casillero",
    "Bed": "Cama",
    "Flood Light": "Foco de Luz",
    "Maze Puzzle": "Rompecabezas Laberinto",
    "Exit": "Salir",
    "Move": "Mover",
    "Select": "Seleccionar",
    "Zoom": "Zoom",
    "Drop": "Soltar",
    "Throw": "Lanzar",
    "Read": "Leer",
    "Put Back": "Colocar de Vuelta",
    "UV Flashlight": "Linterna UV",
    "Your inventory slots have been expanded.": "Tus espacios de inventario han sido expandidos.",
    "This item does not fit there.": "Este objeto no cabe ahí.",
    "New objective": "Nuevo objetivo",
    "Objective completed": "Objetivo completado",
    "A lighter is needed to light the candle": "Se necesita un encendedor para encender la vela",
    "No fuel containers": "Sin contenedores de combustible",
    "No refuelling required": "Sin necesidad de reabastecer",
    "The door is barricaded.": "La puerta está barricada.",
    "Combine": "Combinar",
    "Shortcut": "Atajo",
    "Discard": "Descartar",
    "Press the shortcut key to set the shortcut for the selected item.": "Presiona la tecla de atajo para asignar el atajo al objeto seleccionado.",
    "Select the item you want to combine the current item with.": "Selecciona el objeto con el que quieres combinar el objeto actual.",
    "A powerful beam of light in a sturdy metal body, perfect for illuminating dark areas and revealing hidden dangers.": "Un potente haz de luz en un robusto cuerpo metálico, perfecto para iluminar zonas oscuras y revelar peligros ocultos.",
    "Camcorder": "Videocámara",
    "Illuminate the darkness. Equipped with night vision technology, this camcorder is perfect for exploring and documenting in low light conditions.": "Ilumina la oscuridad. Equipada con tecnología de visión nocturna, esta videocámara es perfecta para explorar y documentar en condiciones de baja luminosidad.",
    "Lantern": "Farol",
    "A reliable source of light for any adventurer. Lantern flame is bright and steady, providing a comforting glow that illuminates your surroundings.": "Una fuente de luz confiable para cualquier aventurero. La llama del farol es brillante y estable, proporcionando un reconfortante resplandor que ilumina tu entorno.",
    "Lighter": "Encendedor",
    "A reliable source of fire for any adventurer. With its compact size and easy-to-use design, the lighter is a must-have item.": "Una fuente de fuego confiable para cualquier aventurero. Con su tamaño compacto y diseño fácil de usar, el encendedor es un objeto imprescindible.",
    "Candle": "Vela",
    "Compact, yet valuable for light and warmth in the darkness with its long-lasting burn time.": "Compacta, pero valiosa para dar luz y calor en la oscuridad gracias a su larga duración de quema.",
    "Axe": "Hacha",
    "Sturdy wood-handled tool with a sharp metal blade, ideal for chopping and potential self-defense.     ": "Herramienta de mango de madera resistente con una afilada hoja metálica, ideal para cortar y como posible defensa personal.",
    "Pocket Knife": "Navaja",
    "Compact folding blade, versatile for cutting tasks and close-quarters defense. Always handy to have.": "Hoja plegable compacta, versátil para tareas de corte y defensa en espacios reducidos. Siempre útil tenerla.",
    "Pistol": "Pistola",
    "A trusty sidearm for close-range combat. This powerful weapon packs a punch and can be a lifesaver in dangerous situations.": "Un arma de mano confiable para combate a corta distancia. Esta poderosa arma tiene mucha potencia y puede salvarte la vida en situaciones peligrosas.",
    "Thermometer": "Termómetro",
    "Measures the temperature of your surroundings. Useful for detecting environmental changes.": "Mide la temperatura de tu entorno. Útil para detectar cambios ambientales.",
    "EMF Meter": "Medidor de EMF",
    "Detects electromagnetic fields. Essential for identifying paranormal activity or electronic disturbances. A must-have for ghost hunters and investigators.": "Detecta campos electromagnéticos. Esencial para identificar actividad paranormal o alteraciones electrónicas. Imprescindible para cazafantasmas e investigadores.",
    "First AID KIT": "Botiquín de Primeros Auxilios",
    "A vital survival tool packed with essential medical supplies. Use to restore health and treat minor injuries. Useful in emergencies.": "Una herramienta de supervivencia vital repleta de suministros médicos esenciales. Úsalo para restaurar la salud y tratar heridas menores. Útil en emergencias.",
    "Medical Oil": "Aceite Medicinal",
    "Effective, fast-acting drug. It is used to alleviate a variety of illnesses, increase the speed of recovery, and boost health at critical moments.": "Medicamento eficaz y de acción rápida. Se utiliza para aliviar diversas enfermedades, aumentar la velocidad de recuperación y potenciar la salud en momentos críticos.",
    "Medical Herb": "Hierba Medicinal",
    "Rare and powerful flora with healing properties. It is used to restore a moderate amount of health or to make powerful healing potions and medicines.": "Flora rara y poderosa con propiedades curativas. Se utiliza para restaurar una cantidad moderada de salud o para elaborar potentes pociones curativas y medicamentos.",
    "Healing Potion": "Poción Curativa",
    "A powerful concoction made from Medical Oil and Medical Herb. Provides quick and significant health boost.": "Una poderosa mezcla elaborada con Aceite Medicinal y Hierba Medicinal. Proporciona una rápida y significativa mejora de salud.",
    "Alkaline Battery": "Batería Alcalina",
    "A compact and reliable source of power that provide long-lasting energy and are perfect for powering flashlights, radios, and other essential items.": "Una fuente de energía compacta y confiable que proporciona energía duradera y es perfecta para alimentar linternas, radios y otros objetos esenciales.",
    "Camera Battery": "Batería de Cámara",
    "Keep your camcorder camera powered up and ready to go with this reliable battery. Designed to provide long-lasting energy.": "Mantén tu videocámara encendida y lista con esta batería confiable. Diseñada para proporcionar energía duradera.",
    "Petrol Oil": "Aceite de Petróleo",
    "A refined petroleum product commonly used as a fuel for lanterns and lamps. It is a clear, colorless liquid that produces a bright, steady flame when burned.": "Un producto de petróleo refinado comúnmente usado como combustible para faroles y lámparas. Es un líquido claro e incoloro que produce una llama brillante y estable al quemarse.",
    "Pistol Ammo": "Munición de Pistola",
    "Compatible with a variety of firearms. With its compact size and high stopping power, 9mm ammo is perfect for close-range combat situations.": "Compatible con una variedad de armas de fuego. Con su tamaño compacto y alto poder de detención, la munición 9mm es perfecta para situaciones de combate a corta distancia.",
    "Pistol Flashlight": "Linterna de Pistola",
    "Shed some light on any situation with this tactical attachment for your pistol. It illuminates your target and reveals hidden dangers in the darkness.": "Ilumina cualquier situación con este accesorio táctico para tu pistola. Ilumina tu objetivo y revela peligros ocultos en la oscuridad.",
    "Key 01": "Llave 01",
    "Key 02": "Llave 02",
    "Key 03": "Llave 03",
    "Key 04": "Llave 04",
    "A generic, yet mysterious key with an unknown use. Keep it on hand, as it may unlock doors, chests, or secrets yet to be discovered.": "Una llave genérica pero misteriosa con un uso desconocido. Tenla a mano, ya que puede abrir puertas, cofres o secretos aún por descubrir.",
    "Keys": "Llaves",
    "Assorted metal keys on a ring. Opens various locks. Essential for access and exploration.": "Variadas llaves metálicas en un llavero. Abre distintos cerrojos. Esenciales para el acceso y la exploración.",
    "Lockpick": "Ganzúa",
    "A handy tool for any adventurer, the lockpick can open a variety of locks and doors.": "Una herramienta útil para cualquier aventurero, la ganzúa puede abrir una variedad de cerraduras y puertas.",
    "Fuse": "Fusible",
    "An essential item for fixing electrical equipment and powering machinery. With its compact size, it's easy to carry in your inventory.": "Un objeto esencial para reparar equipos eléctricos y alimentar maquinaria. Con su tamaño compacto, es fácil de llevar en tu inventario.",
    "An essential component for controlling the flow of liquids and gases in pipes and machinery.": "Un componente esencial para controlar el flujo de líquidos y gases en tuberías y maquinaria.",
    "VHS Cassette": "Cassette VHS",
    "Red Keycard": "Tarjeta Roja",
    "A high-security access card that grants entry to restricted areas.": "Una tarjeta de acceso de alta seguridad que permite entrar a áreas restringidas.",
    "Green Keycard": "Tarjeta Verde",
    "An access card that allows entry to various secure locations.": "Una tarjeta de acceso que permite entrar a diversas ubicaciones seguras.",
    "Fuel Canister": "Bidón de Combustible",
    "Marble Ball": "Bolita de Vidrio",
    "A small, colorful glass ball often used in games. Can be thrown or rolled to solve puzzles and activate mechanisms.": "Una pequeña y colorida bolita de vidrio usada frecuentemente en juegos. Puede lanzarse o rodarse para resolver rompecabezas y activar mecanismos.",
    "Gunpowder": "Pólvora",
    "A volatile black powder used for ammunition and explosives. Combine with scrap to create a pistol ammo.": "Un volátil polvo negro usado para munición y explosivos. Combínalo con chatarra para crear munición de pistola.",
    "Scrap": "Chatarra",
    "A collection of miscellaneous metal pieces. Useful for crafting and repairs.": "Una colección de piezas metálicas variadas. Útil para fabricación y reparaciones.",
    "This is the first example of a tip.": "Este es el primer ejemplo de un consejo.",
    "This is the second example of a tip.": "Este es el segundo ejemplo de un consejo.",
    "This is the third example of a tip.": "Este es el tercer ejemplo de un consejo.",
    "Language": "Idioma",
    "Brightness": "Brillo",
    "Camera FOV": "Campo de Visión de Cámara",
    "Look Sensitivity": "Sensibilidad de Mirada",
    "Look Smoothing": "Suavizado de Mirada",
    "Smoothing Speed": "Velocidad de Suavizado",
    "Show FPS": "Mostrar FPS",
    "Display": "Pantalla",
    "Display Mode": "Modo de Pantalla",
    "Screen Resolution": "Resolución de Pantalla",
    "Frame Rate": "Velocidad de Fotogramas",
    "Vertical Synchronization": "Sincronización Vertical",
    "Render Scale": "Escala de Renderizado",
    "FSR Sharpness": "Nitidez FSR",
    "Antialiasing": "Antialiasing",
    "Antialiasing Quality": "Calidad de Antialiasing",
    "Anisotropic Filtering": "Filtrado Anisotrópico",
    "Texture Quality": "Calidad de Texturas",
    "Shadow Distance": "Distancia de Sombras",
    "Bloom": "Bloom",
    "Vignette": "Viñeta",
    "Film Grain": "Grano de Película",
    "Chromatic Aberration": "Aberración Cromática",
    "General Volume": "Volumen General",
    "Music Volume": "Volumen de Música",
    "Video Settings": "Configuración de Video",
    "Post Processing": "Posprocesado",
    # multiline
    "In this demo scene, you will be able to witness and explore all the impressive features that come with the kit. This scene has been specially designed to showcase the full potential of the asset, so you can fully test its capabilities.":
        "En esta escena de demostración, podrás presenciar y explorar todas las impresionantes funciones del kit. Esta escena ha sido diseñada especialmente para mostrar el pleno potencial del recurso, para que puedas probar todas sus capacidades.",
    "In this interactive demo scene, you will have the opportunity to engage firsthand with the elevator system, showcasing its seamless operation and integration along with the other great features of the kit.":
        "En esta escena de demostración interactiva, tendrás la oportunidad de experimentar de primera mano el sistema de ascensor, mostrando su funcionamiento fluido e integración junto con las demás características del kit.",
    "It's raining outside, you can test how the raindrop effect works when you're sheltered under a roof or not.":
        "Está lloviendo afuera, puedes probar cómo funciona el efecto de gotas de lluvia cuando estás bajo techo o no.",
    "This is an example text for a paper to demonstrate the examination system. You can display the text on the paper using a texture or rewrite the text as paper examination text.\n\n- From Patrick":
        "Este es un texto de ejemplo para un papel que demuestra el sistema de examinación. Puedes mostrar el texto en el papel usando una textura o reescribir el texto como texto de examinación en papel.\n\n- De Patrick",
    "9MM PISTOL AMMO\ncrafting guide\n\nRecipe for making 10x 9mm Pistol Ammo. To make a Pistol Ammo you need to combine the following materials:\n\n5x Gunpowder\n1x Scrap":
        "MUNICIÓN 9MM PARA PISTOLA\nguía de fabricación\n\nReceta para hacer 10x Munición 9mm para Pistola. Para fabricar Munición de Pistola necesitas combinar los siguientes materiales:\n\n5x Pólvora\n1x Chatarra",
    "IF YOU ARE READING THIS\nDON'T LOOK BEHIND YOU":
        "SI ESTÁS LEYENDO ESTO\nNO MIRES DETRÁS DE TI",
    "Name: {name}\nA classic, durable format for video recording and archiving memories or documenting important events.":
        "Nombre: {name}\nUn formato clásico y duradero para grabación de video y archivo de recuerdos o documentación de eventos importantes.",
    "A durable, metal canister filled with a high-efficiency liquid fuel designed specifically to refuel electric generators.\nFuel litres: {fuel_litres}":
        "Un resistente bidón metálico lleno de combustible líquido de alta eficiencia diseñado específicamente para reabastecer generadores eléctricos.\nLitros de combustible: {fuel_litres}",
}

def translate(text):
    stripped = text.strip()
    if stripped in translations:
        return translations[stripped]
    return text

input_path = r"c:\Users\jenri\Downloads\Localization.csv"
output_path = r"c:\Users\jenri\Downloads\Localization_ES.csv"

with open(input_path, "r", encoding="utf-8-sig", newline="") as infile, \
     open(output_path, "w", encoding="utf-8-sig", newline="") as outfile:
    reader = csv.reader(infile)
    writer = csv.writer(outfile, quoting=csv.QUOTE_MINIMAL)
    for row in reader:
        if len(row) >= 3:
            row[-1] = translate(row[-1])
        writer.writerow(row)

print("Done! Output saved to:", output_path)
